### ISSUE TITLE
assignment-7: knitr

### ISSUE THREAD

**Issue by sfaiad** [sfaiad/assignment-7#1]
I was so fascinated by the knitr lectures that I decided to do a bit of a deeper dive into the package for assignment-7. Thanks!

**Comment by mdscheuerell** [comment]
Hi Sara. Would you please add the website for `{knitr}` that you mention in your review? Thx.

**Comment by sfaiad** [comment]
Sure thing! [Here ](https://yihui.org/knitr/) is the website I mentioned. I will add it to the README now!

**Comment by mdscheuerell** [comment]
Nice overview of `{knitr}`, Sara!
